#  docker-compose -f .docker/docker-compose-aws.yml -p aws up -d
#  docker-compose -f .docker/docker-compose-aws.yml -p aws down

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    restart: unless-stopped
    image: localstack/localstack:4.4.0
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "~/.docker-data/localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"